### PR TITLE
Feature/policy registry

### LINKED ISSUE #2: Collect a list of known repositories with Rego
To create a valuable registry we need to start with some known list of repositories.  We should include them as part of the repository under e.g. /metadata. For each repository we add metadata to make sure they are searchable.

### PR DESCRIPTION
**Pull request by xchapter7x**
https://github.com/policy-hub/policy-hub-cli/issues/2

This PR adds a metadata file to store all of our known policy repositories.
THis will be provided to the users of the CLI, in order to allow them to search the known set of public policies

### CODE REVIEW

**Comment by xchapter7x** [comment]
@Blokje5 got time for a PR review?

**Review by Blokje5 — APPROVED** [review]
LGTM! Nice exhaustive descriptions in the registry!

**Comment by xchapter7x** [comment]
> LGTM! Nice exhaustive descriptions in the registry!

yes, cut and paste from the README for the win :)

**Comment by Blokje5** [comment]
Haha I guess that does make live easy if there is already a good description!

**Pull request merged**
